rabbitmq:
  host: rabbitmq.default.svc.cluster.local
  port: 5672
  secretName: rabbitmq-default-user

server:
  image: alkamist1/digit-image-predictor:server-0.1.1
  replicaCount: 1
  port: 80
  podPort: 8080
  healthPath: "/health"
  serviceType: LoadBalancer
  resources:
    limits:
      memory: "256Mi"
      cpu: "100m"
    requests:
      memory: "256Mi"
      cpu: "100m"

worker:
  image: alkamist1/digit-image-predictor:worker-0.1.1
  replicaCount: 1
  resources:
    limits:
      memory: "256Mi"
      cpu: "100m"
    requests:
      memory: "256Mi"
      cpu: "100m"